# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0747dedf3f66272f3f176d11b3a84dbeaaf98db80e73f99258f298468a6d8dced93d780664d1e1211f05392d573b93cf57922c09ba0dae3984d727eb57359631

test:
  secret_key_base: cc9c2151a5f1fe1218e2bd70968a41ac1609ae1d2dc401b1d25a6c5b6234015fce953c8339f68b5ea9a3a77f285f467b113558ed72b1606bdf123261b27200da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
